#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Update all packages
#?? 1.0.0
##?
##? Usage:
##?    update_all

docs::eval_help "$@"

echo '🍎 Updating App Store apps'
mas upgrade

echo ''
echo '🍺 Updating Brew apps'
brew update >/dev/null
brew outdated | xargs -n1 brew upgrade

echo ''
echo '🍻 Updating Brew Cask apps'
OUTDATED_CASKS=$(brew cask outdated)

if [ -n "$OUTDATED_CASKS" ]; then
  echo "$OUTDATED_CASKS" | grep -v real-vnc | xargs -n1 brew cask install --force
  echo '✅  Casks updated'
else
  echo '✅  Casks already up-to-date'
fi

echo ''
echo '🧹 Cleaning up Brew'
brew cleanup

echo ''
echo '⚡️ ZSH Zim'
zsh ${ZIM_HOME}/zimfw.zsh upgrade
zsh ${ZIM_HOME}/zimfw.zsh update
zsh ${ZIM_HOME}/zimfw.zsh uninstall & zsh ${ZIM_HOME}/zimfw.zsh install

echo ''
echo '📜 tldr'
tldr --update

# @todo Create a `sync` command for sync the dotfiles
#echo ''
#echo '♢ Update dotfiles'
#cd ${DOTFILES_PATH}
#git pull --rebase --autostash
#brew bundle install --file=${HOMEBREW_BUNDLE_FILE_PATH}
#brew bundle dump --file=${HOMEBREW_BUNDLE_FILE_PATH} --force
#brew bundle cleanup --file=${HOMEBREW_BUNDLE_FILE_PATH} --force

if [ "${1-none}" == "--all" ]; then
  echo ''
  echo '♦️  Updating gem (Ruby)'
  gem update
fi

echo ''
echo '♻️  Restarting some apps'
killall Rocket
open /Applications/Rocket.app
