#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Backups gnupg to Documents folder
#?? 1.0.0
##?
##? Usage:
##?    gpg

docs::eval "$@"

rsync -avu --delete ~/.gnupg/ ~/Documents/gnupg/
