#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Connects ssh to Documents folder
#?? 1.0.0
##?
##? Usage:
##?    connect

docs::eval "$@"

rsync -avu --delete ~/.ssh ~/Documents/ssh
