#!/usr/bin/env bash

set -euo pipefail

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.macos` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

source "$DOTFILES_PATH/scripts/core/_main.sh"
source "$DOTFILES_PATH/scripts/self/utils/install.sh"
source "$DOTFILES_PATH/scripts/self/utils/docopts.sh"

##? Install the dotfiles
#?? 1.0.0
##?
##? Usage:
##?    install

docs::eval_help "$@"

"$DOTFILES_PATH/bin/dot" self update

log::note "💻 Installing Zim Framework for ZSH"
curl -fsSL https://raw.githubusercontent.com/zimfw/install/master/install.zsh | zsh

if platform::is_macos; then
  log::note "🍎 Installing MacOS custom packages"

  read -rp "🌍 Network: Which name do you want to give to this computer? " network_computer_name
  install_macos_custom "$network_computer_name"
fi

if platform::is_linux; then
  log::note "🐧 Installing Linux custom packages"

  install_linux_custom
fi

log::note "💻 Setting ZSH as the default shell"
command -v zsh | sudo tee -a /etc/shells
chsh -s "$(command -v zsh)"

log::note "🔀 Setting Git config"
read -rp "✉️ What is you email? " git_email
read -rp "👤 And your name? " git_name
read -rp "🔑 Aaaand… the ID of the signing key? " git_key_id

git config --global user.email "$git_email"
git config --global user.name "$git_name"
git config --global user.signingkey "$git_key_id"
git config --global --unset user.signingkey
git config --global --unset commit.gpgsign
git config --global --unset tag.gpgsign
git config --global --unset gpg.program

log::success "🎉 Done!"
